<?php

namespace App\Coinbaz;

class CoinMarketCapApi extends Api
{

    const CMC_COIN_URL = 'https://coinmarketcap.com/currencies/';

    private $parameters = [
        'start' => 1,
        'limit' => 100,
        'convert' => 'USD',
        'sort' => 'date_added',
        'sort_dir' => 'desc'
    ];

    public function parameters(): Api
    {
        return parent::setParameters($this->parameters); // TODO: Change the autogenerated stub
    }


    function url()
    {
       return env('COINMARKETCAP_API_URL');
    }

    function apiKey()
    {
        return env('COINMARKETCAP_API_KEY');
    }
}
